name: 'structurizr-cli-action'
description: 'Runs structurizr command line application'
author: 'Maksim Milykh'
branding:
  icon: 'copy'
  color: 'blue'
inputs:
  command:
    description: 'Command'
  workspace_param:
    description: Static parameter
    default: -id
  workspace_id:
    description: 'The workspace ID'
  key_param:
    description: Static parameter
    default: -key
  key:
    description: 'The workspace API key'
  secret_param:
    description: Static parameter
    default: -secret
  secret:
    description: 'The workspace API secret'
  workspace_file_param:
    description: Static parameter
    default: -workspace
  workspace_file:
    description: 'The path to the workspace JSON file/DSL file(s)'
runs:
  using: 'docker'
  image: 'docker://ghcr.io/aidmax/structurizr-cli-docker:latest'
