name: 'structurizr-cli-action'
description: 'Runs structurizr command line application'
author: 'Maksim Milykh'
branding:
  icon: 'copy'
  color: 'blue'
inputs:
  id:
    description: 'The workspace ID (required)'
    required: true
  key:
    description: 'The workspace API key (required)'
    required: true
  secret:
    description: 'The workspace API secret (required)'
    required: true
  workspace:
    description: 'The path to the workspace JSON file/DSL file(s) (required)'
    required: true
  docs:
    description: 'The path to the directory containing Markdown/AsciiDoc files to be published (optional)'
    required: false
  adrs:
    description: 'The path to the directory containing ADRs (optional)'
    required: false
  url:
    description: 'The Structurizr API URL (optional; defaults to https://api.structurizr.com)'
    required: false
    default: 'https://api.structurizr.com'
  passphrase:
    description: 'The passphrase to use (optional; only required if client-side encryption enabled on the workspace)'
    required: false
runs:
  using: 'docker'
  image: 'docker://ghcr.io/aidmax/structurizr-cli-docker:latest'
  args:
    - 'push'
    - '-id'
    - ${{ inputs.id }}
    - '-key'
    - ${{ inputs.key }}
    - '-secret'
    - ${{ inputs.secret }}
    - '-workspace'
    - ${{ inputs.workspace }}
    - '-url'
    - ${{ inputs.url }}
    - '-passphrase'
    - ${{ inputs.passphrase }}
