name: 'structurizr-cli-action'
description: 'Runs structurizr command line application'
author: 'Maksim Milykh'
branding:
  icon: 'copy'
  color: 'blue'
runs:
  using: 'docker'
  image: 'docker://ghcr.io/aidmax/structurizr-cli-docker:latest'
